name: "Gladys Assistant"
description: "A privacy-first, open-source home automation software"
version: "1.0.0"
slug: "gladys"
url: "https://gladysassistant.com"
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: false
host_network: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
full_access: true
docker_api: true
devicetree: true
uart: true
usb: true
gpio: true
audio: false
video: false
hassio_api: false
apparmor: false
map:
  - share:rw
  - ssl:ro
options:
  server_port: 8080
  timezone: "Europe/Paris"
schema:
  server_port: int
  timezone: str
panel_icon: "mdi:home-assistant"
panel_title: "Gladys"
webui: "http://[HOST]:[PORT:8080]"
startup: "application"
boot: "auto"
ingress: false
